

export const site = {
    title: "Create Next App",
    tagline: "Generated by create next app",
    description: "Generated by create next app",
    keywords: "next.js, react, css-in-js, styled-components",
    owner: "Dave Hill",
    };